
package edu.uni.SistemaGerenciadorDeNotas.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SgnManagerWs", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SgnManagerWs {


    /**
     * 
     * @return
     *     returns java.util.List<edu.uni.SistemaGerenciadorDeNotas.client.Aluno>
     */
    @WebMethod
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "obterTodosOsAlunos", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.ObterTodosOsAlunos")
    @ResponseWrapper(localName = "obterTodosOsAlunosResponse", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.ObterTodosOsAlunosResponse")
    @Action(input = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/obterTodosOsAlunosRequest", output = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/obterTodosOsAlunosResponse")
    public List<Aluno> obterTodosOsAlunos();

    /**
     * 
     * @param aluno
     * @return
     *     returns edu.uni.SistemaGerenciadorDeNotas.client.Aluno
     */
    @WebMethod
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "cadastrarAluno", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.CadastrarAluno")
    @ResponseWrapper(localName = "cadastrarAlunoResponse", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.CadastrarAlunoResponse")
    @Action(input = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/cadastrarAlunoRequest", output = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/cadastrarAlunoResponse")
    public Aluno cadastrarAluno(
        @WebParam(name = "aluno", targetNamespace = "")
        Aluno aluno);

    /**
     * 
     * @param matricula
     * @return
     *     returns edu.uni.SistemaGerenciadorDeNotas.client.Aluno
     */
    @WebMethod
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "removerAluno", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.RemoverAluno")
    @ResponseWrapper(localName = "removerAlunoResponse", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", className = "edu.uni.SistemaGerenciadorDeNotas.client.RemoverAlunoResponse")
    @Action(input = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/removerAlunoRequest", output = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/SgnManagerWs/removerAlunoResponse")
    public Aluno removerAluno(
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

}
