
package edu.uni.SistemaGerenciadorDeNotas.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SgnManagerWsService", targetNamespace = "http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", wsdlLocation = "http://localhost:12345/sgnws?wsdl")
public class SgnManagerWsService
    extends Service
{

    private final static URL SGNMANAGERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SGNMANAGERWSSERVICE_EXCEPTION;
    private final static QName SGNMANAGERWSSERVICE_QNAME = new QName("http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", "SgnManagerWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:12345/sgnws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SGNMANAGERWSSERVICE_WSDL_LOCATION = url;
        SGNMANAGERWSSERVICE_EXCEPTION = e;
    }

    public SgnManagerWsService() {
        super(__getWsdlLocation(), SGNMANAGERWSSERVICE_QNAME);
    }

    public SgnManagerWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SGNMANAGERWSSERVICE_QNAME, features);
    }

    public SgnManagerWsService(URL wsdlLocation) {
        super(wsdlLocation, SGNMANAGERWSSERVICE_QNAME);
    }

    public SgnManagerWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SGNMANAGERWSSERVICE_QNAME, features);
    }

    public SgnManagerWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SgnManagerWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SgnManagerWs
     */
    @WebEndpoint(name = "SgnManagerWsPort")
    public SgnManagerWs getSgnManagerWsPort() {
        return super.getPort(new QName("http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", "SgnManagerWsPort"), SgnManagerWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SgnManagerWs
     */
    @WebEndpoint(name = "SgnManagerWsPort")
    public SgnManagerWs getSgnManagerWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.SistemaGerenciadorDeNotasBack.uni.edu/", "SgnManagerWsPort"), SgnManagerWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SGNMANAGERWSSERVICE_EXCEPTION!= null) {
            throw SGNMANAGERWSSERVICE_EXCEPTION;
        }
        return SGNMANAGERWSSERVICE_WSDL_LOCATION;
    }

}
